# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "O+YPzTFpgBgD8GbReOofyCjqTz3bDHEmI/sqf7V4yq8RvDVnpTycg7yOMnHTHsXWy9KDosP7OSyKVn+X1zvAmiF6H22ioP3lM4ml/+WYjusAMkFDZxPmmWHSYr1VonDE6agKYeFtCEEXmzTtU2aAIYUZQ7bkWlSDO+MvEZ3bmIVTNGg7Mq+wcgKfpkYajkEGyFqGLFnOT2Fe0ofoqQYBkklr43lxdQUd41/mA2Pu2uAxuRg3KpWlULj/QELmJ5l3tPWw+JkyxSpJ4OMRki9zL9S9ovEoaRC9IRs5AVWhGvV6klhT2SUvcfAle8GoCip+My6Jzwur/8c203320emJX9QPmQ44MqQ4kU3wD/WZurGVHSy/lrGxfImwFVB/qjIwk5ySFm2IgW4n60O7TsOb7y0yUnVaJBzjCjZSdec0kc4L7GkJRl2gcM9zlU83OZBY8y541AMqzG26lza4En4vWF37qyaTE61ddXLMRVFmYiypFvn5N2Oqwz4moyGSnqy8rzyzsfcSfkQV8/84ldzQCgWmBCO4jQCAsNaBUwFSoSxcQFixED1zfxWQKoLLJyslmBX4nXeMrQUt6fHPgH/mbB+ivM4FRTM+rnZJLL8mV+A4nZVqzQ+M896FDoIOfrInHeqAQuahRqNtKvA4wam6VBqKOMpP7t6F6ONtcOiuZHc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
