travis:
  secure:
    BINSTAR_TOKEN: O+YPzTFpgBgD8GbReOofyCjqTz3bDHEmI/sqf7V4yq8RvDVnpTycg7yOMnHTHsXWy9KDosP7OSyKVn+X1zvAmiF6H22ioP3lM4ml/+WYjusAMkFDZxPmmWHSYr1VonDE6agKYeFtCEEXmzTtU2aAIYUZQ7bkWlSDO+MvEZ3bmIVTNGg7Mq+wcgKfpkYajkEGyFqGLFnOT2Fe0ofoqQYBkklr43lxdQUd41/mA2Pu2uAxuRg3KpWlULj/QELmJ5l3tPWw+JkyxSpJ4OMRki9zL9S9ovEoaRC9IRs5AVWhGvV6klhT2SUvcfAle8GoCip+My6Jzwur/8c203320emJX9QPmQ44MqQ4kU3wD/WZurGVHSy/lrGxfImwFVB/qjIwk5ySFm2IgW4n60O7TsOb7y0yUnVaJBzjCjZSdec0kc4L7GkJRl2gcM9zlU83OZBY8y541AMqzG26lza4En4vWF37qyaTE61ddXLMRVFmYiypFvn5N2Oqwz4moyGSnqy8rzyzsfcSfkQV8/84ldzQCgWmBCO4jQCAsNaBUwFSoSxcQFixED1zfxWQKoLLJyslmBX4nXeMrQUt6fHPgH/mbB+ivM4FRTM+rnZJLL8mV+A4nZVqzQ+M896FDoIOfrInHeqAQuahRqNtKvA4wam6VBqKOMpP7t6F6ONtcOiuZHc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
